### ISSUE TITLE
Validate viewlet fields entry

### ISSUE THREAD

**Issue by hvelarde** [simplesconsultoria/collective.blueline#1]
Currently seems to be very easy to break a site by adding invalid code on any of the viewlets; we need to run some sort of validation to avoid this.

**Comment by hvelarde** [comment]
We can probably implement a very basic validator using [ElementTree](https://docs.python.org/2/library/xml.etree.elementtree.html).

It will rise `ParseError` if the code is invalid.

**Comment by rodfersou** [comment]
or using lxml http://lxml.de/validation.html http://lxml.de/parsing.html
